development: &config
  adapter: postgresql
  encoding: utf8
  template: template0
  hostname: localhost
  database: awemgmt
  username: postgres
  password:
  pool: 5
  timeout: 5000

test:
  <<: *config
  database: awemgmt_test

production:
  <<: *config
  database: awemgmt_production
